version: '3'
services:
  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  rails:
    build:
      context: ./rails
    command: bash -c "tail -f log/development.log"
    volumes:
      - ./rails:/myapp
    ports:
      - "3001:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      - LOCAL_USER_ID=1000
      - LOCAL_GROUP_ID=1000
  next:
    build:
      context: ./next
    volumes:
      - ./next:/app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    environment:
      - LOCAL_USER_ID=1000
      - LOCAL_GROUP_ID=1000
volumes:
  mysql_data:
