version: '3'
services:
  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  rails:
    build:
      context: ./rails
    command: bash -c "bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./rails:/myapp
    ports:
      - "3001:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  mysql_data:
